name: Create Branch on New Issue

on:
  issues:
    types:
      - opened

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Issue Title
        id: extract-title
        run: |
          ISSUE_TITLE=$(jq -r .issue.title $GITHUB_EVENT_PATH)
          echo "Issue title: $ISSUE_TITLE"
          echo "::set-output name=issue_title::$ISSUE_TITLE"

