name: Create Branch on New Issue

on:
  issues:
    types:
      - opened

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Branch
        id: create-branch
        run: |
          # Extract the issue title and use it as the branch name
          ISSUE_TITLE=$(jq -r .issue.title $GITHUB_EVENT_PATH)
          BRANCH_NAME="issue/$ISSUE_TITLE"
          
          # Create the new branch
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME

      - name: Set Branch Name as Output
        run: echo "branch_name=${BRANCH_NAME}" >> $GITHUB_ENV
