name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: SSH into Virtual Machine
        run: |
          sshpass -p "JYm52DbxCDE3AqE" ssh -o StrictHostKeyChecking=no WiselyDev@172.174.218.96 "cd ws-pymecopilot-sw-mockserver && \
            ls && \
            git status && \
            git pull && \
            npm install && \
            pm2 restart mockserver"
