name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install expect
        run: sudo apt-get install -y expect

      - name: SSH into Virtual Machine
        id: ssh-vm
        run: |
          # Use the expect command to automate SSH login with a password
          expect -c '
            spawn ssh WiselyDev@172.174.218.96
            expect "password:"
            send "JYm52DbxCDE3AqE\r"
            expect "$ "
            send "echo Connected to VM\r"
            interact
          '

      - name: Check SSH status
        run: |
          if [[ "${{ steps.ssh-vm.outcome }}" == "success" ]]; then
            echo "Successfully connected to VM."
            # Add your deployment steps here
          else
            echo "Failed to connect to VM."
            exit 1
          fi
