name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into Virtual Machine

        run: |
          sshpass -p JYm52DbxCDE3AqE ssh WiselyDev@172.174.218.96 "echo 'Connected to VM'"
