name: Access Secret

on: [push]

jobs:
  access-secret:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Access Secret
      env:
        SECRET_VALUE: ${{ deploy.SECRET_VALUE }}
      run: |
        echo "The secret value is: $SECRET_VALUE"
