name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install expect
        run: sudo apt-get install -y expect

      - name: SSH into Virtual Machine
        run: |
          # Use the expect command to automate SSH login with a password
          expect -c '
            spawn ssh -o StrictHostKeyChecking=no WiselyDev@172.174.218.96
            expect "password:"
            send "JYm52DbxCDE3AqE\r"
            expect "$ "
            send "cd ws-pymecopilot-sw-mockserver\r"
            expect "$ "
            send "ls\r"
            expect "$ "
            send "git status\r"
            expect "$ "
            send "echo Connected to VM\r"
            interact
          '

      - name: Update Repository on Virtual Machine
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh WiselyDev@172.174.218.96

