name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ssh-key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: SSH into Virtual Machine
        run: |
          ssh -i ~/.ssh/id_rsa \
            -o StrictHostKeyChecking=no \
            WiselyDev@172.174.218.96 "\
            cd ws-pymecopilot-sw-mockserver && \
            ls && \
            git status && \
            git pull && \
            npm install && \
            pm2 restart mockserver"
