name: Access Secret

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Environment
        env:
          MY_SECRET: ${{ vars.ENV_VAR }}
        run: |
          echo "Using secret: $MY_SECRET"
          # Your deployment steps here

