name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install expect
        run: sudo apt-get install -y expect

      - name: SSH into Virtual Machine
        run: |
          # Use the expect command to automate SSH login with a password
          expect -c '
            spawn ssh WiselyDev@172.174.218.96
            expect "$ "
            send "echo Connected to VM\r"
            interact
          '

      - name: Change directory to project directory
        run: ls
      
      # Add additional steps for your deployment process here
