name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Update VM project
        run: |
          sshpass -p JYm52DbxCDE3AqE ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP_ADDRESS }} "cd ws-pymecopilot-sw-mockserver && \
            ls && \
            git status && \
            git pull && \
            npm install && \
            pm2 restart mockserver"
