name: List GitHub Projects
on:
  workflow_dispatch:  # Trigger manually

jobs:
  list-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: List GitHub Projects
        run: |
          # Fetch the list of projects using GitHub API
          PROJECTS=$(curl -s -H "Accept: application/vnd.github.inertia-preview+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/projects)
          
          # Print the list of project names
          echo "$PROJECTS" | jq -r '.[].name'
