name: List GitHub Projects
on:
  workflow_dispatch:

jobs:
  list-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Projects
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch the list of projects using the GitHub API
          PROJECTS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/projects")

          # Display the list of projects in the workflow log
          echo "List of GitHub Projects in the repository:"
          echo "$PROJECTS" | jq -r '.[].name'


